### ISSUE TITLE
Run time Error

### ISSUE THREAD

**Issue by hostingrajamani** [morissette/insecure-wp-admin-password-check#2]
Error 1146: Table 'srisolut_amrutha.wp_users' doesn't exist
Traceback (most recent call last):
  File "./find_bad_wp_passwords.py", line 142, in <module>
    find_wp_dbs()
  File "./find_bad_wp_passwords.py", line 38, in find_wp_dbs
    (errors, insecure) = test_passwords(data, password_list)
  File "./find_bad_wp_passwords.py", line 104, in test_passwords
    url = data['url'][0]
TypeError: 'NoneType' object is unsubscriptable

**Comment by morissette** [comment]
Reviewing...
